In [ ]:
import pandas as pd

df = pd.read_csv("Superstore.csv", encoding="latin1")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 25 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  Year           9994 non-null   int64
 22  Month          9994 non-null   int64
 23  Month_Name     9994 non-null   object
 24  Profit_Margin  9994 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(5), object(15)
memory usage: 1.9+ MB

In [ ]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [ ]:
df.shape

(9994, 25)

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Year             0
Month            0
Month_Name       0
Profit_Margin    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [ ]:
df['Year'] = df['Order Date'].dt.year

df['Month'] = df['Order Date'].dt.month

df['Month_Name'] = df['Order Date'].dt.month_name()

df['Profit_Margin'] = (df['Profit'] / df['Sales']) * 100

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Month_Name,Profit_Margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,16.00
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,30.00
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,47.00
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,-40.00
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,11.25

In [ ]:
df.to_csv("cleaned_superstore.csv", index=False)

In [ ]:
from google.colab import files

files.download("cleaned_superstore.csv")

In [ ]:
import sqlite3

conn = sqlite3.connect("retail_bi.db")

In [ ]:
import pandas as pd

df = pd.read_csv("cleaned_superstore.csv")

df.to_sql(
    "sales_data",
    conn,
    if_exists="replace",
    index=False
)

print("Table created successfully!")

Table created successfully!

In [ ]:
query = """
SELECT *
FROM sales_data
LIMIT 5;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,Month_Name,Profit_Margin
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,November,16.00
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,November,30.00
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,June,47.00
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,October,-40.00
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,October,11.25

In [ ]:
query = """
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

In [ ]:
query = """
SELECT Region,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM sales_data
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West    725457.82
1     East    678781.24
2  Central    501239.89
3    South    391721.91

In [ ]:
query = """
SELECT Category,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY Category
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Profit
0       Technology     145454.95
1  Office Supplies     122490.80
2        Furniture      18451.27

In [ ]:
query = """
SELECT Segment,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM sales_data
GROUP BY Segment
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

       Segment  Total_Sales
0     Consumer   1161401.34
1    Corporate    706146.37
2  Home Office    429653.15

In [ ]:
query = """
SELECT State,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY State
ORDER BY Total_Profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        State  Total_Profit
0  California      76381.39
1    New York      74038.55
2  Washington      33402.65
3    Michigan      24463.19
4    Virginia      18597.95
5     Indiana      18382.94
6     Georgia      16250.04
7    Kentucky      11199.70
8   Minnesota      10823.19
9    Delaware       9977.37

In [ ]:
query = """
SELECT State,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY State
HAVING SUM(Profit) < 0
ORDER BY Total_Profit ASC;
"""

pd.read_sql(query, conn)

            State  Total_Profit
0           Texas     -25729.36
1            Ohio     -16971.38
2    Pennsylvania     -15559.96
3        Illinois     -12607.89
4  North Carolina      -7490.91
5        Colorado      -6527.86
6       Tennessee      -5341.69
7         Arizona      -3427.92
8         Florida      -3399.30
9          Oregon      -1190.47

In [ ]:
query = """
SELECT Category,
       ROUND(AVG(Discount),2) AS Avg_Discount
FROM sales_data
GROUP BY Category
ORDER BY Avg_Discount DESC;
"""

pd.read_sql(query, conn)

          Category  Avg_Discount
0        Furniture          0.17
1  Office Supplies          0.16
2       Technology          0.13

In [ ]:
query = """
SELECT City,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM sales_data
GROUP BY City
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

            City  Total_Sales
0  New York City    256368.16
1    Los Angeles    175851.34
2        Seattle    119540.74
3  San Francisco    112669.09
4   Philadelphia    109077.01
5        Houston     64504.76
6        Chicago     48539.54
7      San Diego     47521.03
8   Jacksonville     44713.18
9    Springfield     43054.34

In [ ]:
query = """
SELECT "Product Name",
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY "Product Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                        Product Name  Total_Profit
0              Canon imageCLASS 2200 Advanced Copier      25199.93
1  Fellowes PB500 Electric Punch Plastic Comb Bin...       7753.04
2               Hewlett Packard LaserJet 3310 Copier       6983.88
3                 Canon PC1060 Personal Laser Copier       4570.93
4  HP Designjet T520 Inkjet Large Format Printer ...       4094.98
5                  Ativa V4110MDD Micro-Cut Shredder       3772.95
6   3D Systems Cube Printer, 2nd Generation, Magenta       3717.97
7  Plantronics Savi W720 Multi-Device Wireless He...       3696.28
8               Ibico EPK-21 Electric Binding System       3345.28
9                  Zebra ZM400 Thermal Label Printer       3343.54

In [ ]:
query = """
SELECT Year,
       Month,
       ROUND(SUM(Sales),2) AS Monthly_Sales
FROM sales_data
GROUP BY Year, Month
ORDER BY Year, Month;
"""

pd.read_sql(query, conn)

    Year  Month  Monthly_Sales
0   2014      1       14236.90
1   2014      2        4519.89
2   2014      3       55691.01
3   2014      4       28295.35
4   2014      5       23648.29
5   2014      6       34595.13
6   2014      7       33946.39
7   2014      8       27909.47
8   2014      9       81777.35
9   2014     10       31453.39
10  2014     11       78628.72
11  2014     12       69545.62
12  2015      1       18174.08
13  2015      2       11951.41
14  2015      3       38726.25
15  2015      4       34195.21
16  2015      5       30131.69
17  2015      6       24797.29
18  2015      7       28765.33
19  2015      8       36898.33
20  2015      9       64595.92
21  2015     10       31404.92
22  2015     11       75972.56
23  2015     12       74919.52
24  2016      1       18542.49
25  2016      2       22978.82
26  2016      3       51715.88
27  2016      4       38750.04
28  2016      5       56987.73
29  2016      6       40344.53
30  2016      7       39261.96
31  2016      8       31115.37
32  2016      9       73410.02
33  2016     10       59687.75
34  2016     11       79411.97
35  2016     12       96999.04
36  2017      1       43971.37
37  2017      2       20301.13
38  2017      3       58872.35
39  2017      4       36521.54
40  2017      5       44261.11
41  2017      6       52981.73
42  2017      7       45264.42
43  2017      8       63120.89
44  2017      9       87866.65
45  2017     10       77776.92
46  2017     11      118447.83
47  2017     12       83829.32

In [ ]:
query = """
SELECT
ROUND(SUM(Sales),2) AS Total_Sales,
ROUND(SUM(Profit),2) AS Total_Profit,
COUNT(DISTINCT "Order ID") AS Total_Orders,
COUNT(DISTINCT "Customer ID") AS Total_Customers
FROM sales_data;
"""

pd.read_sql(query, conn)

   Total_Sales  Total_Profit  Total_Orders  Total_Customers
0   2297200.86     286397.02          5009              793

In [ ]:
from google.colab import files
files.download("cleaned_superstore.csv")

Create monthly sales + profit data

In [ ]:
import pandas as pd

df = pd.read_csv("cleaned_superstore.csv")

df['Order Date'] = pd.to_datetime(df['Order Date'])

monthly_data = df.groupby(['Year', 'Month']).agg({
    'Sales': 'sum',
    'Profit': 'sum'
}).reset_index()

monthly_data['Month_Index'] = range(1, len(monthly_data) + 1)

monthly_data.head()

   Year  Month      Sales     Profit  Month_Index
0  2014      1  14236.895  2450.1907            1
1  2014      2   4519.892   862.3084            2
2  2014      3  55691.009   498.7299            3
3  2014      4  28295.345  3488.8352            4
4  2014      5  23648.287  2738.7096            5

In [ ]:
from sklearn.linear_model import LinearRegression

X = monthly_data[['Month_Index']]

y_sales = monthly_data['Sales']
y_profit = monthly_data['Profit']

sales_model = LinearRegression()
profit_model = LinearRegression()

sales_model.fit(X, y_sales)
profit_model.fit(X, y_profit)

LinearRegression()

In [ ]:
future_months = pd.DataFrame({
    'Month_Index': range(len(monthly_data) + 1, len(monthly_data) + 7)
})

future_sales = sales_model.predict(future_months)
future_profit = profit_model.predict(future_months)

In [ ]:
last_year = monthly_data['Year'].iloc[-1]
last_month = monthly_data['Month'].iloc[-1]

future_dates = pd.date_range(
    start=f"{last_year}-{last_month}-01",
    periods=7,
    freq='MS'
)[1:]

forecast_df = pd.DataFrame({
    'Forecast_Date': future_dates,
    'Forecast_Month': future_dates.month_name(),
    'Predicted_Sales': future_sales,
    'Predicted_Profit': future_profit
})

forecast_df

  Forecast_Date Forecast_Month  Predicted_Sales  Predicted_Profit
0    2018-01-01        January     69957.535798       9377.263483
1    2018-02-01       February     70859.543330       9516.474049
2    2018-03-01          March     71761.550862       9655.684615
3    2018-04-01          April     72663.558395       9794.895181
4    2018-05-01            May     73565.565927       9934.105747
5    2018-06-01           June     74467.573459      10073.316313

In [ ]:
forecast_df.to_csv("sales_forecast.csv", index=False)

from google.colab import files
files.download("sales_forecast.csv")